spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-store
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  application:
    name: bookstore

server:
  port: 8083


